### PR TITLE
Using complex (curly-brace) to remove ambiguity when interpolating varia...

### PR DESCRIPTION
**Pull request by jbrooksuk**
...bles within strings.

Just a quickie.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
GitHubs editor messed up my curly braces!!

**Comment by sambenne** [comment]
Cheers. Will be updating that bit later when I get a design sorted.

**Comment by jbrooksuk** [comment]
No problem if it worked. But GitHub completes braces for you and it messed up slightly. You get the point though :)

**Comment by sambenne** [comment]
Well I just did it manually and pushed the changes. Suck on the GitHub.

**Pull request closed without merging**
